#!/bin/bash

# Saves the path of the current directory into the bkdir file.
SCRIPTDIR=`scriptdir`
BK_FILE=Data/bkdir
if [ -e "$SCRIPTDIR/$BK_FILE" ];
then
    LASTDIR=`cat $SCRIPTDIR/$BK_FILE`
fi
CURRDIR=`pwd`
if [ "$LASTDIR" != "$CURRDIR" ];
then
    pwd > `scriptdir`/$BK_FILE;
fi
