#!/bin/bash

# ssh into a random uvanimor machine and immediately go to the scratch
# directory in /scratch/cluster/$username (username = your user id)

num=$(($RANDOM % 10))
ssh -t `whoami`@uvanimor-"$num".cs.utexas.edu "cd /scratch/cluster/`whoami`; echo 'You are here: `pwd`'; bash"
