#!/bin/bash


# This script searches the Documents directory in the user's home folder and
# attempts to CD into the desired directory. The desired directory is
# described by an optionally case-insensitive regex check that matches the
# first few letters (parameter #1) and last few letters (parameter #2) to an
# existing directory on the filesystem.
#
# For example, to go to ~/Documents/files/MyDirectory53
# Just type in: $ . goto my 53
#
#
# RUNNING:
# . goto [options] <start> [end]
#
# [options]:    (otional) - Use to choose the following options:
#               c = case sensitive
#               a = search all (not just documents directory)
#
# <start>:      One or more characters at the beginning of directory.
#
# [end]:        (optional) - One or more characters at end of directory.



### TODO ###
# implement option checks



if ! [ $1 ];
then
    echo "Where am I taking you?"
    exit
fi


cd ~/Documents
#gotodir=`find \( ! -regex './*\..*' \) -type d -name $1* -print -quit`
gotodir=`find -type d -iname $1*$2 -print -quit`
if ! [ $gotodir ];
then
    echo "I couldn't find $1."
    exit
fi

cd $gotodir
pwd
