#!/bin/bash

# Simple script that prints the directory where it is stored (i.e. the
# directory where all user scripts are stored).
# Credit:
# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $SCRIPTDIR
