#!/bin/bash

# Configures git with the correct global settings...
# Useful on fresh installations of a new OS.

editor="vim"
name="Richard Teammco"
email="teammco@cs.utexas.edu"

git config --global color.ui auto
git config --global core.editor "$editor"
git config --global user.name "$name"
git config --global user.email "$email"
