#!/bin/bash

# Calls 'randcs' to get the name of a random available UTCS host machine,
# and does ssh into it with the provided username.
# Any arguments passed in will be forwarded to the ssh call.

uta_path=`scriptdir`/UTA
login=`$uta_path/mecs`

echo "Logging in to: $login"
ssh $@ $login
